# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "pastoragenda"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a table or view. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's major version.
# Check your remote database's version with `supabase db remote commit`.
major_version = 15

[db.pooler]
# Port to use for the local connection pooler.
port = 54329

[realtime]
# Set this to false to disable the realtime server.
enabled = true
# Port to use for the realtime server.
port = 54323

[studio]
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://127.0.0.1:54321"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (one week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses.
# If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Disable email rate limiting for development
# [auth.email.template.confirmation]
# subject = "Confirm your signup"
# content_path = "./supabase/templates/confirmation.html"

# Rate limiting configuration moved to main auth.email section above

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

# Uncomment to customize email template
# [auth.email.template.confirmation]
# subject = "Confirm your signup"
# content_path = "./supabase/templates/confirmation.html"

# Uncomment to customize email template
# [auth.email.template.recovery]
# subject = "Reset your password"
# content_path = "./supabase/templates/recovery.html"

# Uncomment to customize email template
# [auth.email.template.email_change]
# subject = "Confirm your email change"
# content_path = "./supabase/templates/email_change.html"

# Uncomment to customize email template
# [auth.email.template.magic_link]
# subject = "Your magic link"
# content_path = "./supabase/templates/magic_link.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending SMS confirmations.
# template = "Your code is {{ .Code }}"

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""

# Use pre-defined map of claims that are added to JWT tokens
[auth.jwt]
admin_claim_name = "role"
default_group_name = "authenticated"
# Custom JWT secret for our authentication system
secret = "env(JWT_SECRET)"

# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
# [sms]
# provider = "twilio"
# [sms.twilio]
# account_sid = ""
# message_service_sid = ""
# # DO NOT commit the auth_token to git. Use environment variable substitution instead:
# auth_token = "env(SUPABASE_AUTH_TOKEN)"
# # Template for sending SMS confirmations.
# template = "Your code is {{ .Code }}"

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `slack`,
# `spotify`, `twitch`, `twitter`, `workos`, `zoom`.
# [auth.external.apple]
# enabled = true
# client_id = "env(APPLE_CLIENT_ID)"
# secret = "env(APPLE_SECRET)"
# # Overrides the default auth redirectUrl.
# redirect_uri = "env(APPLE_REDIRECT_URI)"
# # Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# # or any other third-party OIDC providers.
# url = "env(APPLE_URL)"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
# [inbucket]
# port = 54324
# smtp_port = 54325
# pop3_port = 54326

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `slack`,
# `spotify`, `twitch`, `twitter`, `workos`, `zoom`.
# [auth.external.apple]
# enabled = true
# client_id = "env(APPLE_CLIENT_ID)"
# secret = "env(APPLE_SECRET)"
# # Overrides the default auth redirectUrl.
# redirect_uri = "env(APPLE_REDIRECT_URI)"
# # Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# # or any other third-party OIDC providers.
# url = "env(APPLE_URL)"
